/*
 * Go through a directory and collect all ROOT graphs generated by the
 * tag and probe analyzer.
 */

void collectPlots(TString thePath, TString theOutFileName, TString theNameTag){
    std::cout << "[INFO] Collect plots..." << std::endl;

    TFile *myOutFile = new TFile(theOutFileName,"RECREATE");
    TSystemDirectory dir(thePath, thePath);
    TSystemFile *file;
    TString fname;
    TIter next(dir.GetListOfFiles());
    UInt_t fileCounter = 0;
    TString fileCounterStr;
    while (((file=(TSystemFile*)next()))){
        fname = file->GetName();
        if ( fname.BeginsWith(theNameTag) && fname.Contains("root") ){
            std::cout << "[INFO] Processing file: " << fname << std::endl;
            TFile *myFile = new TFile(thePath + fname);
            TIter nextkey(myFile->GetListOfKeys());
            TKey *key;
            while ((key = (TKey*)nextkey())){
                TString theTypeClasse = key->GetClassName();
                TString theNomClasse = key->GetTitle();
                if ( theTypeClasse == "TDirectoryFile"){
                    TDirectory *theDr = (TDirectory*) myFile->Get(theNomClasse);
                    TIter nextkey2(theDr->GetListOfKeys());
                    TKey *key2;
                    while ((key2 = (TKey*)nextkey2())){
                        TString theTypeClasse2 = key2->GetClassName();
                        TString theNomClasse2 = key2->GetTitle();
                        if ( theTypeClasse == "TDirectoryFile"){
                            TDirectory *theDr2 = (TDirectory*) myFile->Get(theNomClasse+"/"+theNomClasse2+"/fit_eff_plots");
                            TIter nextkey3(theDr2->GetListOfKeys());
                            TKey *key3;
                            while ((key3 = (TKey*)nextkey3())){
                                TString theTypeClasse3 = key3->GetClassName();
                                TString theNomClasse3 = key3->GetName();
                                TCanvas *theCanvas = (TCanvas*) myFile->Get(theNomClasse+"/"+theNomClasse2+"/fit_eff_plots/"+theNomClasse3);
                                TIter nextObject(theCanvas->GetListOfPrimitives());
                                TObject *obj;
                                while ((obj = (TObject*)nextObject())){
                                    if (obj->InheritsFrom("TGraphAsymmErrors")){
                                        myOutFile->cd();
                                        fileCounterStr.Form("%i", fileCounter);
                                        obj->Write(fileCounterStr+"_"+theNomClasse2+"_"+theNomClasse3+"_"+obj->GetTitle());
                                        fileCounter++;
                                        myFile->cd();
                                    }
                                    if (obj->InheritsFrom("TH2F")){
                                        myOutFile->cd();
                                        obj->Write(theNomClasse2+"_"+theNomClasse3);
                                        myFile->cd();
                                    }
                                }
                            }
                        }
                    }
                }
            }
            delete myFile;
        }
    }
    myOutFile->Close();
}
